SEQUENCE_NUMBER_SIZE = 4
CHECKSUM_SIZE = 4
CHUNK_SIZE = 4096
HEADER_SIZE = SEQUENCE_NUMBER_SIZE + CHECKSUM_SIZE
PAYLOAD_SIZE = CHUNK_SIZE - HEADER_SIZE
RTO = 1
UPLOAD = 'upload'
DOWNLOAD = 'download'
